"""Replay coverage for the T4.1 timer-loop batch transport.

Every committed history under ``tests/replay/histories/`` is replayed through a
temporalio ``Replayer`` built with forge's real workflow classes. Replay pins
the *command sequence* each workflow emits: a future change to workflow logic
that would emit a different sequence — the failure mode that silently breaks an
in-flight (up-to-25h) batch wait in production — raises a non-determinism error
here instead of on a live worker.

The histories are regenerated by ``tests/replay/regenerate.py`` (one command:
``uv run python -m tests.replay.regenerate`` — or ``make replay-histories``).
Regenerate ONLY after a deliberate workflow-logic change; never to silence an
unexplained failure here (that failure is what this suite exists to catch).
"""

from pathlib import Path

import pytest
from temporalio.client import WorkflowHistory
from temporalio.contrib.pydantic import pydantic_data_converter
from temporalio.worker import Replayer

from forge.workflows import ForgeSubTaskWorkflow, ForgeTaskWorkflow

_HISTORIES_DIR = Path(__file__).parent / "replay" / "histories"
_REGEN_CMD = "uv run python -m tests.replay.regenerate"


def _history_files() -> list[Path]:
    return sorted(_HISTORIES_DIR.glob("*.json"))


def test_histories_directory_is_populated() -> None:
    """An empty or missing histories directory must fail loudly, not pass silently.

    A scaffold with no committed histories replays nothing and would give a false
    green — the exact gap this guard closes.
    """
    assert _HISTORIES_DIR.is_dir(), (
        f"replay histories directory missing: {_HISTORIES_DIR}. Generate it with `{_REGEN_CMD}`."
    )
    assert _history_files(), (
        f"no committed replay histories in {_HISTORIES_DIR}. "
        f"An empty scaffold must not pass silently — generate them with `{_REGEN_CMD}`."
    )


@pytest.mark.parametrize(
    "history_file",
    _history_files(),
    ids=lambda p: p.stem,
)
async def test_history_replays_deterministically(history_file: Path) -> None:
    """Each committed history replays without a non-determinism error.

    ``raise_on_replay_failure=True`` turns any command/event divergence into a
    test failure. The workflow_id passed to ``from_json`` is the file stem: forge
    workflows never branch on ``workflow.info().workflow_id`` (it flows only into
    activity-input payloads, which replay does not byte-compare), so the stem is
    a faithful stand-in and the replay result depends solely on workflow logic.
    """
    replayer = Replayer(
        workflows=[ForgeTaskWorkflow, ForgeSubTaskWorkflow],
        data_converter=pydantic_data_converter,
    )
    history = WorkflowHistory.from_json(history_file.stem, history_file.read_text())
    await replayer.replay_workflow(history, raise_on_replay_failure=True)
